package edu.towson.cosc.cosc455.jchen21.project1

object Compiler{

  var currentToken : String = ""
  var fileContents : String = ""

  val Scanner = new MyLexicalAnalyzer
  val Parser = new MySyntaxAnalyzer
  val SemanticAnalyzer = new MySemanticAnalyzer
  var fileName: String = ""

  def main(args: Array[String]): Unit = {
    checkFile(args) // checks to see if there is a file and if the file has the right extension
    readFile(args(0)) //reads the file from the provided runtime argument

    fileName = args(0).substring(0, args(0).length - 4) //removed the extension (.gtx) from the filename

    Scanner.getNextToken() //primes the lexical analyzer
    Parser.gittex() //calls the syntax analyzer's start state
    SemanticAnalyzer.toHTML() // converts the parse tree generated by the Syntax Analyzer into HTML
  }

  def readFile(file : String) = {
    val source = scala.io.Source.fromFile(file)
    fileContents = try source.mkString finally source.close()
  }

  def checkFile(args : Array[String]) = {
    if (args.length != 1) {
      println("USAGE ERROR: wrong number of args fool!")
      System.exit(1)
    }
    else if (! args(0).endsWith(".gtx")) {
      println("USAGE ERROR: wrong extension fool!")
      System.exit(1)
    }
  }
}
